name: Build & Package

permissions:
  contents: write
# 触发条件：推送到main分支、手动触发
on:
  push:
    branches: [ main ]
    tags:
      - v*.*.*
  workflow_dispatch: # 网页上可以手动点击运行

jobs:
  build:
    runs-on: windows-latest
    steps:
      # 1.拉取仓库代码
      - name: Checkout code
        uses: actions/checkout@v4

      # 2.安装pnpm
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10

      # 3.安装Node环境
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm' # 缓存依赖，加快下次构建

      # 4.安装依赖 + 打包
      - name: Install dependencies & Build
        run: |
          pnpm install --frozen-lockfile
          pnpm run build:prod

      # 5.上传打包产物（Artifacts，构建完可以下载）
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: dist-files
          path: dists/ # vite是dist，vue-cli是dist，react CRA是build
          # path: dist/*.{exe,zip,yml,blockmap}

  release:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          draft: true
          files: |
            artifacts/dist-files/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
